### ISSUE TITLE
Value Error: not enough value to unpack (expected 3, got 1)

### ISSUE THREAD

**Issue by KoyuKansou** [michaelshumshum/r-placer#28]
E:\rplacebot\r-placer-master>python main.py w.png 851 -192
Traceback (most recent call last):
  File "E:\rplacebot\r-placer-master\main.py", line 12, in <module>
    m = management.manager(image_dir, image_location)
  File "E:\rplacebot\r-placer-master\management.py", line 85, in __init__
    email, username, password = row
ValueError: not enough values to unpack (expected 3, got 1)

even though i already have accounts.cvs and the username+password it still didn't work

**Comment by michaelshumshum** [comment]
did you format it correctly like this:

`email(optional) username password`

**Comment by KoyuKansou** [comment]
> 

yes but idk about the email(optional) one since i got the (expected 3, got 2; or even too many values to unpact, expected 3) now

**Comment by KoyuKansou** [comment]
> Owner

nvm fixed, forgot to put them all in 1 collum (the too many value was too long username)
